### ISSUE TITLE
1.2.0 Fails to Compile with Clang

### ISSUE THREAD

**Issue by DomT4** [andreabolognani/cattle#2]
Build fails consistently with Clang. OS X 10.10.2, Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn).

Clang build:

```
==> make install
Making install in cattle
  GEN      cattle-enums.h
  GEN      cattle-enums.c
/Applications/Xcode.app/Contents/Developer/usr/bin/make  install-am
  CC       cattle-version.lo
  CC       cattle-constants.lo
  CC       cattle-error.lo
  CC       cattle-buffer.lo
cattle-buffer.c:241:2: error: non-void function 'cattle_buffer_get_value' should return a value [-Wreturn-type]
        g_return_if_fail (CATTLE_IS_BUFFER (self));
        ^
/usr/local/Cellar/glib/2.42.1/include/glib-2.0/glib/gmessages.h:373:3: note: expanded from macro 'g_return_if_fail'
         return;                                                        \
         ^
cattle-buffer.c:244:2: error: non-void function 'cattle_buffer_get_value' should return a value [-Wreturn-type]
        g_return_if_fail (!priv->disposed);
        ^
/usr/local/Cellar/glib/2.42.1/include/glib-2.0/glib/gmessages.h:373:3: note: expanded from macro 'g_return_if_fail'
         return;                                                        \
         ^
cattle-buffer.c:245:2: error: non-void function 'cattle_buffer_get_value' should return a value [-Wreturn-type]
        g_return_if_fail (position < priv->size);
        ^
/usr/local/Cellar/glib/2.42.1/include/glib-2.0/glib/gmessages.h:373:3: note: expanded from macro 'g_return_if_fail'
         return;                                                        \
         ^
3 errors generated.
make[2]: *** [cattle-buffer.lo] Error 1
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1
```

Build works fine with Gcc 4.9.2.

**Comment by andreabolognani** [comment]
This issue has been fixed with commit [`3e6f44b`](https://github.com/andreabolognani/cattle/commit/3e6f44b2baaa663924ab48df23ea538d4386cec4).
